[package]
name = "kg-g"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.16"
hecs = "0.7.6"
rapier2d = { version = "0.12.0", features = [ "wasm-bindgen" ] }

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[profile.dev.package.'*']
opt-level = 3
