[package]
name = "kg-g"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#build --target wasm32-unknown-unknown

[dependencies]
macroquad = "0.3.16"

#cargo build --target wasm32-unknown-unknown

[profile.dev.package.'*']
opt-level = 3

[profile.release]
opt-level = 'z'
lto = "thin"
